
export const juzData = [
  { number: 1, name: "Alif Lam Meem", arabicName: "آلم", folder: "001-AlifLaamMeem", numberOfSurahs: 2 },
  { number: 2, name: "Sayaqool", arabicName: "سيقول السفهاء", folder: "002-Sayaqool", numberOfSurahs: 1 },
  { number: 3, name: "Tilka Rusul", arabicName: "تلك الرسل", folder: "003-TilkarRusul", numberOfSurahs: 2 },
  { number: 4, name: "Lan Tana Loo", arabicName: "لن تنالوا", folder: "004-Lan-Tana-ullBir", numberOfSurahs: 2 },
  { number: 5, name: "Wal Mohsanat", arabicName: "والمحصنات", folder: "005-Wal-Muhsanaat", numberOfSurahs: 1 },
  { number: 6, name: "La Yuhibbullah", arabicName: "لا يحب الله", folder: "006-La-Yu-hibbullah", numberOfSurahs: 2 },
  { number: 7, name: "Wa Iza Samiu", arabicName: "وإذا سمعوا", folder: "007-Wa-Iza-Samioo", numberOfSurahs: 2 },
  { number: 8, name: "Wa Lau Annana", arabicName: "ولو أننا", folder: "008-Wa'laoo-Annana", numberOfSurahs: 2 },
  { number: 9, name: "Qalal Malao", arabicName: "قال الملأ", folder: "009-Qaa-lal-Mala", numberOfSurahs: 2 },
  { number: 10, name: "Wa A'lamu", arabicName: "واعلموا", folder: "010-Wa-alamoo", numberOfSurahs: 2 },
  { number: 11, name: "Yatazeroon", arabicName: "يعتذرون", folder: "011-Ya-Taziroon", numberOfSurahs: 3 },
  { number: 12, name: "Wa Mamin Da'abat", arabicName: "ومامن دابة", folder: "012-Wa-Ma-Min", numberOfSurahs: 3 },
  { number: 13, name: "Wa Ma Ubrioo", arabicName: "وما أبرئ", folder: "013-Wama-Ubarrioo", numberOfSurahs: 3 },
  { number: 14, name: "Rubama", arabicName: "ربما", folder: "014-Ruba-maa", numberOfSurahs: 2 },
  { number: 15, name: "Subhanallazi", arabicName: "سبحٰن الذیٓ", folder: "015-Subhanal-lazi", numberOfSurahs: 2 },
  { number: 16, name: "Qal Alam", arabicName: "قال ألم", folder: "016-Qala-Alam", numberOfSurahs: 3 },
  { number: 17, name: "Iqtaraba", arabicName: "اقترب للناس", folder: "017-Iqtaraba", numberOfSurahs: 2 },
  { number: 18, name: "Qadd Aflaha", arabicName: "قد أفلح", folder: "018-Qad-Aflahal", numberOfSurahs: 3 },
  { number: 19, name: "Wa Qalallazina", arabicName: "وقال الذين", folder: "019-Wa-Qaalal", numberOfSurahs: 3 },
  { number: 20, name: "A'man Khalaq", arabicName: "امن خلق", folder: "020-Amman-Khalaq", numberOfSurahs: 3 },
  { number: 21, name: "Utlu Ma Oohi", arabicName: "اتل مآ اوحی", folder: "021-Utlu-ma-Oohiya", numberOfSurahs: 3 },
  { number: 22, name: "Wa Man Yaqnut", arabicName: "ومن يقنت", folder: "022-Wa-mai-Yaqnut", numberOfSurahs: 3 },
  { number: 23, name: "Wa Mali", arabicName: "ومالی", folder: "023-Wa-malia", numberOfSurahs: 4 },
  { number: 24, name: "Faman Azlam", arabicName: "فمن أظلم", folder: "024-Faman-Azlamu", numberOfSurahs: 3 },
  { number: 25, name: "Elahe Yuruddo", arabicName: "إليه يرد", folder: "025-Ilai-Hi", numberOfSurahs: 4 },
  { number: 26, name: "Ha'a Meem", arabicName: "حـم", folder: "026-Haa-Meem", numberOfSurahs: 5 },
  { number: 27, name: "Qala Fama", arabicName: "قال فما", folder: "027-Qaala-Fama", numberOfSurahs: 7 },
  { number: 28, name: "Qadd Sami Allah", arabicName: "قد سمع اللہ", folder: "028-Qad-Sami-Allah", numberOfSurahs: 9 },
  { number: 29, name: "Tabarakallazi", arabicName: "تبٰرک الذی", folder: "029-Tabarak-Al-Lazi", numberOfSurahs: 11 },
  { number: 30, name: "Amma Yatasa'aloon", arabicName: "عمّ", folder: "030-Am-ma", numberOfSurahs: 37 },
];
